/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChunkChunkIdRouteImport } from './routes/chunk.$chunkId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChunkChunkIdRoute = ChunkChunkIdRouteImport.update({
  id: '/chunk/$chunkId',
  path: '/chunk/$chunkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chunk/$chunkId': typeof ChunkChunkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chunk/$chunkId': typeof ChunkChunkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chunk/$chunkId': typeof ChunkChunkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chunk/$chunkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chunk/$chunkId'
  id: '__root__' | '/' | '/chunk/$chunkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChunkChunkIdRoute: typeof ChunkChunkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chunk/$chunkId': {
      id: '/chunk/$chunkId'
      path: '/chunk/$chunkId'
      fullPath: '/chunk/$chunkId'
      preLoaderRoute: typeof ChunkChunkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChunkChunkIdRoute: ChunkChunkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
