/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyQuizSettingsRouteImport } from './routes/daily-quiz-settings'
import { Route as DailyQuizResultRouteImport } from './routes/daily-quiz-result'
import { Route as DailyQuizRouteImport } from './routes/daily-quiz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyQuizWeakRouteImport } from './routes/daily-quiz.weak'
import { Route as DailyQuizRevisionRouteImport } from './routes/daily-quiz.revision'
import { Route as DailyQuizSubjectIdRouteImport } from './routes/daily-quiz.$subjectId'
import { Route as ChunkChunkIdRouteImport } from './routes/chunk.$chunkId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyQuizSettingsRoute = DailyQuizSettingsRouteImport.update({
  id: '/daily-quiz-settings',
  path: '/daily-quiz-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyQuizResultRoute = DailyQuizResultRouteImport.update({
  id: '/daily-quiz-result',
  path: '/daily-quiz-result',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyQuizRoute = DailyQuizRouteImport.update({
  id: '/daily-quiz',
  path: '/daily-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyQuizWeakRoute = DailyQuizWeakRouteImport.update({
  id: '/weak',
  path: '/weak',
  getParentRoute: () => DailyQuizRoute,
} as any)
const DailyQuizRevisionRoute = DailyQuizRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => DailyQuizRoute,
} as any)
const DailyQuizSubjectIdRoute = DailyQuizSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => DailyQuizRoute,
} as any)
const ChunkChunkIdRoute = ChunkChunkIdRouteImport.update({
  id: '/chunk/$chunkId',
  path: '/chunk/$chunkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-quiz': typeof DailyQuizRouteWithChildren
  '/daily-quiz-result': typeof DailyQuizResultRoute
  '/daily-quiz-settings': typeof DailyQuizSettingsRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/chunk/$chunkId': typeof ChunkChunkIdRoute
  '/daily-quiz/$subjectId': typeof DailyQuizSubjectIdRoute
  '/daily-quiz/revision': typeof DailyQuizRevisionRoute
  '/daily-quiz/weak': typeof DailyQuizWeakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-quiz': typeof DailyQuizRouteWithChildren
  '/daily-quiz-result': typeof DailyQuizResultRoute
  '/daily-quiz-settings': typeof DailyQuizSettingsRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/chunk/$chunkId': typeof ChunkChunkIdRoute
  '/daily-quiz/$subjectId': typeof DailyQuizSubjectIdRoute
  '/daily-quiz/revision': typeof DailyQuizRevisionRoute
  '/daily-quiz/weak': typeof DailyQuizWeakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-quiz': typeof DailyQuizRouteWithChildren
  '/daily-quiz-result': typeof DailyQuizResultRoute
  '/daily-quiz-settings': typeof DailyQuizSettingsRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/chunk/$chunkId': typeof ChunkChunkIdRoute
  '/daily-quiz/$subjectId': typeof DailyQuizSubjectIdRoute
  '/daily-quiz/revision': typeof DailyQuizRevisionRoute
  '/daily-quiz/weak': typeof DailyQuizWeakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/daily-quiz'
    | '/daily-quiz-result'
    | '/daily-quiz-settings'
    | '/dashboard'
    | '/search'
    | '/chunk/$chunkId'
    | '/daily-quiz/$subjectId'
    | '/daily-quiz/revision'
    | '/daily-quiz/weak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/daily-quiz'
    | '/daily-quiz-result'
    | '/daily-quiz-settings'
    | '/dashboard'
    | '/search'
    | '/chunk/$chunkId'
    | '/daily-quiz/$subjectId'
    | '/daily-quiz/revision'
    | '/daily-quiz/weak'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/daily-quiz'
    | '/daily-quiz-result'
    | '/daily-quiz-settings'
    | '/dashboard'
    | '/search'
    | '/chunk/$chunkId'
    | '/daily-quiz/$subjectId'
    | '/daily-quiz/revision'
    | '/daily-quiz/weak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DailyQuizRoute: typeof DailyQuizRouteWithChildren
  DailyQuizResultRoute: typeof DailyQuizResultRoute
  DailyQuizSettingsRoute: typeof DailyQuizSettingsRoute
  DashboardRoute: typeof DashboardRoute
  SearchRoute: typeof SearchRoute
  ChunkChunkIdRoute: typeof ChunkChunkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-quiz-settings': {
      id: '/daily-quiz-settings'
      path: '/daily-quiz-settings'
      fullPath: '/daily-quiz-settings'
      preLoaderRoute: typeof DailyQuizSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-quiz-result': {
      id: '/daily-quiz-result'
      path: '/daily-quiz-result'
      fullPath: '/daily-quiz-result'
      preLoaderRoute: typeof DailyQuizResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-quiz': {
      id: '/daily-quiz'
      path: '/daily-quiz'
      fullPath: '/daily-quiz'
      preLoaderRoute: typeof DailyQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-quiz/weak': {
      id: '/daily-quiz/weak'
      path: '/weak'
      fullPath: '/daily-quiz/weak'
      preLoaderRoute: typeof DailyQuizWeakRouteImport
      parentRoute: typeof DailyQuizRoute
    }
    '/daily-quiz/revision': {
      id: '/daily-quiz/revision'
      path: '/revision'
      fullPath: '/daily-quiz/revision'
      preLoaderRoute: typeof DailyQuizRevisionRouteImport
      parentRoute: typeof DailyQuizRoute
    }
    '/daily-quiz/$subjectId': {
      id: '/daily-quiz/$subjectId'
      path: '/$subjectId'
      fullPath: '/daily-quiz/$subjectId'
      preLoaderRoute: typeof DailyQuizSubjectIdRouteImport
      parentRoute: typeof DailyQuizRoute
    }
    '/chunk/$chunkId': {
      id: '/chunk/$chunkId'
      path: '/chunk/$chunkId'
      fullPath: '/chunk/$chunkId'
      preLoaderRoute: typeof ChunkChunkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DailyQuizRouteChildren {
  DailyQuizSubjectIdRoute: typeof DailyQuizSubjectIdRoute
  DailyQuizRevisionRoute: typeof DailyQuizRevisionRoute
  DailyQuizWeakRoute: typeof DailyQuizWeakRoute
}

const DailyQuizRouteChildren: DailyQuizRouteChildren = {
  DailyQuizSubjectIdRoute: DailyQuizSubjectIdRoute,
  DailyQuizRevisionRoute: DailyQuizRevisionRoute,
  DailyQuizWeakRoute: DailyQuizWeakRoute,
}

const DailyQuizRouteWithChildren = DailyQuizRoute._addFileChildren(
  DailyQuizRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DailyQuizRoute: DailyQuizRouteWithChildren,
  DailyQuizResultRoute: DailyQuizResultRoute,
  DailyQuizSettingsRoute: DailyQuizSettingsRoute,
  DashboardRoute: DashboardRoute,
  SearchRoute: SearchRoute,
  ChunkChunkIdRoute: ChunkChunkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
